version: '2'

services:
  PamonhaAPI:
    image: hsbtiago/pamonhaapi:latest    
    environment: 
      ASPNETCORE_ENVIRONMENT: Production  
    ports:
      - "20000:80"
    networks:
      - Pamonha-network
    depends_on:
      - "RedisPamonha"

  RedisPamonha:
    image: redis:alpine
    ports:
      - "16379:6379"
    networks:
      - Pamonha-network

  PamonhaFront:
    image: hsbtiago/pamonhafront:latest            
    ports:
      - "8080:8080"
    networks:
    - Pamonha-network
    depends_on:
      - "PamonhaAPI"

networks: 
    Pamonha-network:
        driver: bridge
