version: '2.1'

services:
  front:
    image: front
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 30000:30000
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js